### ISSUE TITLE
Yarn Use failing with "Yarn package layout unexpected."

### ISSUE THREAD

**Issue by JacobVarghese1992** [geeklearningio/gl-vsts-tasks-yarn#109]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [X] Bug
* [ ] Feature request

# Description

**Use Yarn** step fails with ##[error]Yarn package layout unexpected.
<img width="880" alt="Screen Shot 2022-02-23 at 11 55 04 AM" src="https://user-images.githubusercontent.com/19432015/155270852-ac92f182-12e3-418f-b539-7dcfe44925b9.png">

# Expected behavior

Should not fail

# Reproduction

*Insert reproduction steps here*

```
N/A
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [ ] Hosted
* [X] Custom

**OS:**
* [ ] Windows
* [X] Mac
* [] Linux

**Yarn version:**
*1.22.17**

**Node version:**
*Node version**

**Comment by sandorfr** [comment]
Not enough information to reproduce
