### ISSUE TITLE
TFS/VSTS Package Management authentication

### ISSUE THREAD

**Issue by Megasware128** [geeklearningio/gl-vsts-tasks-yarn#13]
Great to use Yarn as a build task but unlike the npm tasks available, Yarn doesn't seem to automatically authenticate for npm registries created by the Package Management feature in TFS2017/VSTS. Is there a solution for using Package Management registries in combination with the Yarn build task?

**Comment by sandorfr** [comment]
This is of course a great suggestion. We need to investigate how we can adapt the authentication procedure from the npm task to yarn https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Npm/npmtask.ts#L190 .

This is a priority one for us.

**Comment by waterfoul** [comment]
Looks like the code you want to be looking at is in https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Npm/npmregistry.ts

**Comment by KarandikarMihir** [comment]
We can't switch to yarn because of this :(

**Comment by sandorfr** [comment]
Happy to accept a PR is anyone has the time to work on this.

**Comment by KarandikarMihir** [comment]
@sandorfr Would have loved to work on this. But I lack the context.

**Comment by Megasware128** [comment]
I might take a look but need to find some time

**Comment by Cryza** [comment]
A manual way to set the access token using a build agent that we use at the moment is the following PowerShell script:

```
Add-Content <path-to-your-npmrc> "`r`n//<your-team>.pkgs.visualstudio.com/_packaging/<your-feed-name>/npm/registry/:_authToken=$(System.AccessToken)"
```

It will add the access token to the `.npmrc` so yarn can use it to access the registry. You should run this before doing `yarn` or `yarn install`. Yarn will consider any `.npmrc` files, even upwards in the folder tree, so just put it somewhere within the tree and it should work.

Please mind: this requires to have the following *Build Definition Option* to be set:
![2017-07-28_09-31-55](https://user-images.githubusercontent.com/4516798/28707193-b3fb8286-7377-11e7-85ec-44e9c029acce.jpg)

**Comment by sandorfr** [comment]
I adjusted the roadmap, as I'm focused on this issue right now. This is basically around the corner, but I'm running into issues similar to this https://github.com/yarnpkg/yarn/issues/678 . It seems like it might be necessary to generate a yarnrc in addition to npmrc.

**Comment by sandorfr** [comment]
I've pushed a new major version including VSTS feed support.

**Comment by Mardoxx** [comment]
Broken for me. npm install works fined, yarn install yields 401 with VSTS feeds.

**Comment by sandorfr** [comment]
Can you share de debug log?

**Comment by Mardoxx** [comment]
@sandorfr weird, it's working now. I was having issues with VSTS feeds locally too so perhaps this was unrelated.

**Comment by Mardoxx** [comment]
Ok it's still broken on my build. Here's debug log
```
******************************************************************************
Starting: Yarn install --verbose
******************************************************************************
==============================================================================
Task         : Yarn task
Description  : Executes Yarn
Version      : 1.1.1001
Author       : Geek Learning
Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn) (Version 1.1.1001)
==============================================================================
agent.workFolder=d:\a
loading inputs and endpoints
loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loading INPUT_ARGUMENTS
loading INPUT_CUSTOMFEED
loading INPUT_CUSTOMREGISTRY
loading INPUT_PRODUCTIONMODE
loading INPUT_PROJECTDIRECTORY
loading SECRET_NPM_ACCESSTOKEN
loaded 9
which 'yarn'
found: 'C:\NPM\Modules\yarn.cmd'
Arguments=install --verbose
ProjectDirectory=d:\a\1\s
customRegistry=useNpmrc
customFeed=c314204c-5eb4-4dbd-b660-e0c97452ddd5
customEndpoint=null
C:\NPM\Modules\yarn.cmd
Build.BuildId=608
Agent.BuildDirectory=d:\a\1
testing directory 'd:\a\1\npm'
testing directory 'd:\a\1'
mkdir 'd:\a\1\npm'
Build.BuildId=608
Agent.BuildDirectory=d:\a\1
Npm.PackagingCollectionUrl=undefined
System.TeamFoundationCollectionUri=https://{companyName}}.visualstudio.com/
Resource file haven\'t set, can\'t find loc string for key: FoundLocalRegistries
Processed: ##vso[task.issue type=warning;]Resource file haven\'t set, can\'t find loc string for key: FoundLocalRegistries
FoundLocalRegistries 1
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Resource file haven\'t set, can\'t find loc string for key: FoundBuildCredentials
Processed: ##vso[task.issue type=warning;]Resource file haven\'t set, can\'t find loc string for key: FoundBuildCredentials
FoundBuildCredentials
Npm.PackagingCollectionUrl=undefined
System.TeamFoundationCollectionUri=https://{companyName}}.visualstudio.com/
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Resource file haven\'t set, can\'t find loc string for key: FoundBuildCredentials
Processed: ##vso[task.issue type=warning;]Resource file haven\'t set, can\'t find loc string for key: FoundBuildCredentials
FoundBuildCredentials
Using registries in .npmrc
customEndpoint=null
Adding auth for registry: https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/
which 'C:\NPM\Modules\yarn.cmd'
found: 'C:\NPM\Modules\yarn.cmd'
which 'C:\NPM\Modules\yarn.cmd'
found: 'C:\NPM\Modules\yarn.cmd'
ProductionMode=false
C:\NPM\Modules\yarn.cmd arg: install --verbose
exec tool: C:\NPM\Modules\yarn.cmd
arguments:
install
--verbose
C:\Windows\system32\cmd.exe /D /S /C "C:\NPM\Modules\yarn.cmd install --verbose"
yarn install v1.0.1
verbose 0.684 Checking for configuration file "d:\\a\\1\\s\\.npmrc".
verbose 0.685 Found configuration file "d:\\a\\1\\s\\.npmrc".
verbose 0.685 Checking for configuration file "C:\\Users\\buildguest\\.npmrc".
verbose 0.686 Checking for configuration file "d:\\a\\_tool\\node\\8.5.0\\x64\\etc\\npmrc".
verbose 0.686 Checking for configuration file "d:\\a\\1\\s\\.npmrc".
verbose 0.686 Found configuration file "d:\\a\\1\\s\\.npmrc".
verbose 0.687 Checking for configuration file "d:\\a\\1\\.npmrc".
verbose 0.687 Checking for configuration file "d:\\a\\.npmrc".
verbose 0.691 Checking for configuration file "d:\\a\\1\\s\\.yarnrc".
verbose 0.691 Checking for configuration file "C:\\Users\\buildguest\\.yarnrc".
verbose 0.692 Checking for configuration file "d:\\a\\_tool\\node\\8.5.0\\x64\\etc\\yarnrc".
verbose 0.692 Checking for configuration file "d:\\a\\1\\s\\.yarnrc".
verbose 0.692 Checking for configuration file "d:\\a\\1\\.yarnrc".
verbose 0.692 Checking for configuration file "d:\\a\\.yarnrc".
verbose 0.696 current time: 2017-09-18T15:49:42.957Z
 Resolving packages...
 Fetching packages...
verbose 2.343 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/axios/-/axios-0.16.2.tgz".
verbose 2.356 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/follow-redirects/-/follow-redirects-1.2.4.tgz".
verbose 2.388 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/is-buffer/-/is-buffer-1.1.5.tgz".
verbose 2.394 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/debug/-/debug-2.6.8.tgz".
verbose 2.396 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/ms/-/ms-2.0.0.tgz".
verbose 2.398 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/babel-core/-/babel-core-6.26.0.tgz".
verbose 2.4 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/babel-code-frame/-/babel-code-frame-6.26.0.tgz".
verbose 2.403 Performing "GET" request to "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/babel-generator/-/babel-generator-6.26.0.tgz".
verbose 2.482 Error: https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/follow-redirects/-/follow-redirects-1.2.4.tgz: Request failed "401 Unauthorized"
    at Request.<anonymous> (C:\NPM\Modules\node_modules\yarn\lib\cli.js:57662:26)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.module.exports.Request.onRequestResponse (C:\NPM\Modules\node_modules\yarn\lib\cli.js:118210:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
error An unexpected error occurred: "https://{companyName}}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/follow-redirects/-/follow-redirects-1.2.4.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "d:\\a\\1\\s\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: C:\NPM\Modules\yarn.cmd failed with return code: 1
rc:1
success:false
Error: C:\NPM\Modules\yarn.cmd failed with return code: 1
task result: Failed
Error: C:\NPM\Modules\yarn.cmd failed with return code: 1
Processed: ##vso[task.issue type=error;]Error: C:\NPM\Modules\yarn.cmd failed with return code: 1
Processed: ##vso[task.complete result=Failed;]Error: C:\NPM\Modules\yarn.cmd failed with return code: 1
Agent.BuildDirectory=d:\a\1
rm -rf d:\a\1\npm
removing directory
******************************************************************************
Finishing: Yarn install --verbose
******************************************************************************
```

**Comment by sandorfr** [comment]
can you explain to me how this templated url `https://{companyName}.pkgs.visualstudio.com/_packaging/{FeedName}/npm/registry/` is working or point me to some documentation? I'm not familiar with this.

**Comment by Mardoxx** [comment]
It's not real, I should have said `https://foo.pkgs.visualstudio.com/_packaging/bar/npm/registry/`

**Comment by Mardoxx** [comment]
It isn't real, I just removed my information before posting the log here

On 21 Sep 2017 02:15, "Sandor" <notifications@github.com> wrote:

can you explain to me how this templated url https://{companyName}.pkgs.
visualstudio.com/_packaging/{FeedName}/npm/registry/
<http://pkgs.visualstudio.com/_packaging/%7BFeedName%7D/npm/registry/> is
working or point me to some documentation? I'm not familiar with this.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/geeklearningio/gl-vsts-tasks-yarn/issues/13#issuecomment-331023213>,
or mute the thread

**Comment by sandorfr** [comment]
Given your logs it seems you have selected the first option but I'm pretty sure you want the second one : 
![image](https://user-images.githubusercontent.com/2660262/30691002-7b0711a0-9ec6-11e7-9566-fb35debf6a24.png)

**Comment by sandorfr** [comment]
another possible cause is that you don't have the proper rights defined for your package feed : 
![image](https://user-images.githubusercontent.com/2660262/30691505-36c72e9c-9ec8-11e7-81d9-333a92bfd795.png)
see documentation: https://docs.microsoft.com/en-us/vsts/package/feeds/common-identities

**Comment by Mardoxx** [comment]
Tried both, `Registries in my .npmrc file` and `Registry I select here` neither work, stirll get 401 without extra task of putting auth token in to `.npmrc` 😢 

Checked perms on the feed too, they're all correct!

I'd assume the way it automatically inserts auth stuff is lifted from this https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/Npmso I'd imagine it should auth in an identical way. Npm task works fine with either `Registries in my .npmrc file` and `Registry I select here`, but this doesn't without the extra step. Weird!

I'd guess it's more likely some misconfiguration at my end, otherwise you'd have others reporting issues too?

**Comment by sandorfr** [comment]
can you show me your .npmrc so I can try to reproduce your configuration on my test env?

**Comment by Mardoxx** [comment]
```
registry=https://foo.pkgs.visualstudio.com/_packaging/bar/npm/registry/
always-auth=true

```

**Comment by sandorfr** [comment]
Ok reproduced

**Comment by sandorfr** [comment]
Have you seen the the NpmAuthenticate Task, I'm quite tempted to remove the Authentication support from the task. 

Happy to hear your feedback about it.

**Comment by Mardoxx** [comment]
@sandorfr No I haven't! Would make it rather more maintainable for you if auth was done externally by MS's task. I'm happy with that.

**Comment by sandorfr** [comment]
@Mardoxx, can you confirm that the issue is fixed for you with the latest version ?

Had a feedback from vsts team and they'd prefer us to keep builtin authentication support for security reasons (because the task cleans up credentials).

**Comment by Mardoxx** [comment]
@sandorfr Works perfectly! Thanks for your support 😄 

Still coming up with those resource warnings, e.g. `##[warning]Resource file haven\'t set, can\'t find loc string for key: FoundLocalRegistries`

**Comment by kdelmonte** [comment]
This is also happening to me... was a solution even found?

**Comment by sandorfr** [comment]
It’s long addressed and closed. If you have a problem please file a new detailed issue.

**Comment by Megasware128** [comment]
@kdelmonte Try uninstalling and reinstalling the extensions

**Comment by JackieNagel** [comment]
I was getting the same 401 issues when trying to install from an internal packagefeed. The workaround for me, was to include a .npmrc file and use the built-in npm authenticate task.

All permissions should be alright and OAuth script access is turned on.

Are you sure it's working as intended?

PS. also tried to reinstall the extension without luck

**Comment by sandorfr** [comment]
As I said this has been resolved a long time ago. If you have a problem, it is probably something specific please open an issue with the proper logs.
