### ISSUE TITLE
TFS 2015 Update 2 task doesn't show up

### ISSUE THREAD

**Issue by ivoloshin** [geeklearningio/gl-vsts-tasks-yarn#24]
I installed it and it appears as installed on my collection. However, when I try to add it to a build or release definition it's not showing up in the list of available tasks. Is there something I can do?

**Comment by ivoloshin** [comment]
Installed yarn.msi on the build server. Now it works great!

**Comment by sandorfr** [comment]
A version of yarn is bundled with the task so it's unrelated. I think this must have been some kind of caching issue.
