### ISSUE TITLE
Please upgrade Yarn tool to 1.1.0

### ISSUE THREAD

**Issue by Igorbek** [geeklearningio/gl-vsts-tasks-yarn#26]

**Comment by sandorfr** [comment]
We'll stop bundling Yarn inside the task in favor of a tool installer Task which will give you much more controller on the version you want to use. It should hit the store very soon.

**Comment by Igorbek** [comment]
Thanks, I was aware of the plan. I thought #23 was not going to make it soon since it'd been opened for more than a month. Nice, looking forward to it.

**Comment by sandorfr** [comment]
I haven't published the branch now, but it's on my laptop ;)

**Comment by sandorfr** [comment]
Hi @Igorbek, just letting you know that the tool installer is available as part of the 2.0.0 (preview)

**Comment by Igorbek** [comment]
That's awesome, thanks!
