### ISSUE TITLE
Allow updatable Yarn version

### ISSUE THREAD

**Issue by dtzar** [geeklearningio/gl-vsts-tasks-yarn#36]
Would be nice if you could have everywhere in your code where you download the version of yarn to be from the public location instead of on your private storage account.  This would allow for others to submit PRs to help keep this task up to date.  As of now, yarn is at Sept 7th 1.0.1 with current version [1.2.1](https://github.com/yarnpkg/yarn/releases/tag/v1.2.1).  Alternatively or in addition, you could update the task itself to allow others to specify the version they want like https://github.com/TsuyoshiUshio/KubernetesTask or others.

https://github.com/geeklearningio/gl-vsts-tasks-yarn/blob/bcaa006acb912ac219946923ab8f636797f7b645/Tasks/YarnInstaller/yarnToolInstallerTask.ts#L11

**Comment by sandorfr** [comment]
Hi,

The yarn tool installer task which allows you to specify your yarn version requirement is available since a month now and the task does not contain any bundled version anymore. I guess you just have to update your builds.

**Comment by sandorfr** [comment]
the tarballs.json is just an extract of the github release github feed in the form of a map from version to url. It's automatically updated every 5 hours so there nothing to be done manually.

**Comment by dtzar** [comment]
Thank you!  For others who might hit this thread - I realized I needed to choose the drop-down for the 2.x version of the task AND add the additional yarn downloader task first.  Then all is well.  Thanks for this great task :D
![image](https://user-images.githubusercontent.com/3578906/32302961-d6104f36-bf22-11e7-8008-4f84d408b528.png)

**Comment by sandorfr** [comment]
You are more than welcome ;) I'll use your screenshot to update the wiki. 

There is a issue with 1.3.0 they published tonight (https://github.com/yarnpkg/yarn/issues/4828).
