### ISSUE TITLE
Arguments and Install Options

### ISSUE THREAD

**Issue by argrithmag** [geeklearningio/gl-vsts-tasks-yarn#38]
It appears that when I create a yarn task to build, and append the Production install flag, it's running the task with the arguments out of order.   It'll run "yarn --production build" which causes it to ignore the build portion.  
![image](https://user-images.githubusercontent.com/1087256/33718759-2cdb10ae-db24-11e7-8032-3ea3b93e7363.png)

I have to manually flag the --production on the arguments line:
![image](https://user-images.githubusercontent.com/1087256/33718624-b2fd14da-db23-11e7-94f7-6549d77189c4.png)

... works fine:
![image](https://user-images.githubusercontent.com/1087256/33718810-591113d0-db24-11e7-8df4-87468000a0f4.png)

**Comment by sandorfr** [comment]
Hi yes the production Install option is only for when you restore dependencies. 
In other cases you should just use you own argument.
