### ISSUE TITLE
Build hangs intermittently when calling bash scripts

### ISSUE THREAD

**Issue by jason-hunt** [geeklearningio/gl-vsts-tasks-yarn#39]
I'm using node 8.1.4.  The yarn build step times out when executing bash scripts.  There is no other output, the line in the log is: 

bash ./buildScripts/prebuild.sh

It runs for 60 minutes and times out.  Occasionally, it will get through this one only to fail on a different bash script.  Occasionally, it will build everything just fine in around 4 minutes.  One of the bash scripts only has a call to echo some text.  Even that one will hang.

I am able to use npm tasks instead of the yarn task to build my project, but I was hoping to use yarn instead.  Any suggestions?

**Comment by jason-hunt** [comment]
Using a Windows server build agent...

**Comment by sandorfr** [comment]
It's most likely the same problem as https://github.com/geeklearningio/gl-vsts-tasks-yarn/issues/17.
Can you try on a linux agent ?

I opened an issue on Yarn as it's a problem on their side when yarn is a child process : https://github.com/yarnpkg/yarn/issues/4694

But no answers yet.

**Comment by sandorfr** [comment]
Also would you mind upgrading your node to the last LTS version ? 8.9.3
