### ISSUE TITLE
yarn start failed

### ISSUE THREAD

**Issue by SFaraji** [geeklearningio/gl-vsts-tasks-yarn#41]
In the build agent when I'm installing yarn and after that I run yarn start the operation will automatically cancel.
I tired to update my node to version 8.x and it still didn't work.
Any help would be so great.

**Comment by sandorfr** [comment]
Why would you do a yarn start on a build server ?

**Comment by SFaraji** [comment]
to initiate the process

**Comment by sandorfr** [comment]
Of?

**Comment by sandorfr** [comment]
I don’t think is has anything to do with task. Yarn start is meant to run a server which has no purpose especially on a build server. How will you exit it for instance. 

I can’t really help you with the information you provide. Please refer to the how to report an issue in the wiki. In addition I think you’ll have to providé a repro.

**Comment by sandorfr** [comment]
If you still have the problem, please reopen an issue with the appropriate information.
