### ISSUE TITLE
Why is there a `yarn` demand?

### ISSUE THREAD

**Issue by nshenoy** [geeklearningio/gl-vsts-tasks-yarn#42]
It seems with #27 a new `yarn` demand was added. This means that the build agent will need to have a `yarn` capability already set. This doesn't seem to make sense since the task will install Yarn if it's not present already. Should we consider removing the demand, or is this now a requirement? If it's a requirement, consider putting a note in the Visual Studio Marketplace description and/or readme.md.

**Comment by sandorfr** [comment]
The task does not install yarn anymore. To do so you must use the yarn installer task.
