### ISSUE TITLE
Add Nightly Option

### ISSUE THREAD

**Issue by darthtrevino** [geeklearningio/gl-vsts-tasks-yarn#44]
# Are you reporting a bug or a feature request ?
* [ ] Bug
* [X] Feature request

# Description
When specifying the version to use, "nightly" should be an option to use bleeding-edge features as they are developed.

My use case is that I need a "nohoist" workspace feature that should drop with v1.4.2. I plan on using nightly builds for a short time period until they appear in main builds.

# Expected behavior
Set version to "nightly", the build downloads the latest Yarn build.
# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [X] Hosted
* [ ] Custom

**OS:**
* [ ] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
Under discussion

**Node version:** 
8.x

**Comment by sandorfr** [comment]
Hi,

Thanks for the clarity of the explanation :). This is technically feasible as they provide a feed [https://nightly.yarnpkg.com/tar-builds].

A checkbox switching to nightly the nightly build seems pretty straightforward. 

Maybe another approach could be to have a more powerful version constraint format something like this`1.4.^1-x`  which would take build greater than `1.4.1-0`. But that would be more work.

**Comment by sandorfr** [comment]
won't do
