### ISSUE TITLE
[Mitigated] Yarn Install adds npm as demand

### ISSUE THREAD

**Issue by AStoker** [geeklearningio/gl-vsts-tasks-yarn#47]
# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description

When adding 'Yarn Task' to install dependencies using yarn, it adds npm as a demand the build agent must have. This doesn't seem right, since Yarn is not NPM, and it ultimately fails with the message
```
No agent found in pool Default which satisfies the specified demands:
msbuild
visualstudio
npm
Agent.Version -gtVersion 1.95.0
```
Everything exists on the server except npm. Our build steps include:  
- Use Node 8.x  
- Use Yarn 1.x  
- Yarn Install

As soon as the Yarn Install task is added, npm appears as a demand.

# Expected behavior

NPM should not be listed as a demand if it's not being used

# Reproduction

1. Create a new build definition  
2. Add a Yarn task  
3. See npm as a demand

(No logs to report other than already mentioned)

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [ ] Hosted
* [X] Custom

**OS:**
* [X] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
2.4.999
**Node version:**
8.11.1

**Comment by sandorfr** [comment]
It should be a Node demand indeed. However that would be breaking for the people relying on the node version that comes with hosted agents.

**Comment by AStoker** [comment]
A Node demand, absolutely (that's why I have the use node task there). But `npm` isn't node, it's the node package manager, and what Yarn replaces.  
Not entirely following the second part, what would be the breaking change?

**Comment by sandorfr** [comment]
Because the registered capability on hosted agents is `Node.Js` instead of `Node`

**Comment by AStoker** [comment]
Any idea on a work around until this is resolved?

**Comment by sandorfr** [comment]
you have two options, install a version of node on your agent or manually add the capability npm to your agents.
