### ISSUE TITLE
yarnInstaller installs yarn 1.8 pre-release instead of yarn 1.7 stable

### ISSUE THREAD

**Issue by mdw211** [geeklearningio/gl-vsts-tasks-yarn#48]
yarnInstaller installs yarn 1.8 pre-release instead of yarn 1.7 stable

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description

Yarn 1.8 pre-release is being installed by yarnInstaller when set to install "latest 1.x".  It appears that this is due to:

https://geeklearningassets.blob.core.windows.net/yarn/tarballs.json

listing:

"v1.8.0":"https://github.com/yarnpkg/yarn/releases/download/v1.8.0/yarn-v1.8.0.tar.gz"

but:

https://github.com/yarnpkg/yarn/releases 

shows it marked as pre-release.  I'm unsure how the tarball is generated, but it is the reason that yarnInstaller is picking the pre-release version of yarn.

# Expected behavior

yarn 1.7 should be used

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [x] Hosted
* [ ] Custom

**OS:**
* [x] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
*Yarn version**
1.8!

Thanks,

Mark

**Comment by haukurk** [comment]
+1

Had issues due to this as well!

**Comment by edqwerty1** [comment]
+1 builds were broken... Removing version wildcard and forcing 1.7.0 as a workaround

**Comment by k-schneider** [comment]
Got hit with this today as well.  Build server started bombing every job using this task.

**Comment by sandorfr** [comment]
Thanks for reporting this. It seems there are many sub issues to this one:
* filter out pre-releases by default (with a option to go to bleeding edge or switch to nightly #44)
* There is a problem with 1.8.0 on VSTS. 

I'm mitigating the problem by removing the 1.7.0 and disabling the job which fetches releases for now.

The 1.8.0 is worrying me a bit more. Are you using vsts feeds or npm?

**Comment by mdw211** [comment]
Did you mean removing 1.8?  Should that ever have been in tarball.json (https://geeklearningassets.blob.core.windows.net/yarn/tarballs.json) given that it's pre-release?

I'm using VSTS, and the errors I was getting from building were simply that after "yarn install" there were missing packages.

**Comment by sandorfr** [comment]
Can you provide the logs? There is probably bugs to report to yarn.

On the version it's debatable, some people want the latest prerelease because they need it. I expected people to tweak the version pattern according to their needs. It is clearly not happening. So yes I'll add the capability to choose to include prerelease (and even nightlies) in the future. The default will become what you expected.

**Comment by sandorfr** [comment]
The 2.5.0 is out and solves the prerelease issue. There’s an option to get them back if you need
