### ISSUE TITLE
Where is the output directory?

### ISSUE THREAD

**Issue by levalencia** [geeklearningio/gl-vsts-tasks-yarn#51]
extension works, but where is the build output?  I need to publish the build artifacts to release to azure, but documentation is not clear about this.

https://screencast.com/t/RkkL9DZkzo9

**Comment by sandorfr** [comment]
Well it seems to me you are only restoring packages. It's up to you to define your build according to your need ;). You probably have some build script you need to run and you have to copy your output to the $(Build.ArtifactStagingDirectory).
