### ISSUE TITLE
Cannot install plugin Azure Devops

### ISSUE THREAD

**Issue by chalkan3** [geeklearningio/gl-vsts-tasks-yarn#55]
All the task versions belonging to Contribution yarn-task should have the same task id. The tasks at Tasks/Yarn/task.json (version 2.5.999) and Tasks/YarnInstaller/task.json (version 2.5.999) do not have the same ids.

**Comment by sandorfr** [comment]
Hello, I’m not sure to understand what you’re point at and what. 

What problem are you trying to solve?

**Comment by chalkan3** [comment]
When i try install the plugin on Azure Devops. They sent this message

**Comment by chalkan3** [comment]
Like this 
https://imageshack.com/a/img921/207/7YhYy6.png

**Comment by sandorfr** [comment]
This looks more like a marketplace bug than anything else. Let me reach out
to my contacts.

**Comment by chalkan3** [comment]
Thank you !!!

**Comment by sandorfr** [comment]
I've reached out the the marketplace team. I'll let you know how it goes.

**Comment by chalkan3** [comment]
ok!

**Comment by sandorfr** [comment]
Would you mind trying again today?

**Comment by chalkan3** [comment]
Yes it works ! thank you
