### ISSUE TITLE
Azure DevOps: Yarn task missing from build definition selection

### ISSUE THREAD

**Issue by imtravisb** [geeklearningio/gl-vsts-tasks-yarn#56]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description

After installing the Yarn extension via Marketplace to my org's Azure DevOps account, there is only one 1 Yarn task available in the build definition (Yarn Tool Installer). The actual Yarn task is missing.

# Expected behavior

There should be two "tasks" available in the build definition: Yarn task & Yarn Tool Installer

# Reproduction

Added Yarn to Azure DevOps using "manage extensions" in the Org Settings.

```
MANDATORY FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [X] Hosted
* [ ] Custom

**OS:**
* [X] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
Version 2.6.999

![image](https://user-images.githubusercontent.com/4227179/48154792-5aaf6180-e27e-11e8-98b2-fe18c3d8c063.png)

**Comment by sandorfr** [comment]
Sounds like it is a question for Microsoft Support. It's working perfectly fine on my accounts:

![image](https://user-images.githubusercontent.com/2660262/48167105-c22ce600-e33e-11e8-8183-0400c1b8c508.png)

**Comment by NiclasSparrSpoton** [comment]
I got the same issue

**Comment by imtravisb** [comment]
Here's the link to the issue I created over on the MS Dev Community side...
https://developercommunity.visualstudio.com/content/problem/377826/yarn-task-missing-from-available-tasks-after-yarn.html

**Comment by imtravisb** [comment]
> Sounds like it is a question for Microsoft Support. It's working perfectly fine on my accounts:
> 

For what it's worth, I tried to add Yarn to my personal DevOps account, and had the same exact problem. I'm guessing if you already have it installed and it's working correctly, you're fine. Maybe try adding a new Org in DevOps and install the extension and report the results?

**Comment by sandorfr** [comment]
Would you mind communicating your account via twitter DM to vsts team ? 

See : https://twitter.com/youhananaseim/status/1060682461955416064?s=21

**Comment by youfoundkris** [comment]
Idem

**Comment by csolarz** [comment]
+1 !!

**Comment by imtravisb** [comment]
> Would you mind communicating your account via twitter DM to vsts team ?
> 
> See : https://twitter.com/youhananaseim/status/1060682461955416064?s=21

As much fun as it is to jump through these hoops, I've abandoned Yarn. This was affecting a particularly important CI process. Powershell task and good 'ol NPM to the rescue. Good luck to everyone else!

**Comment by sandorfr** [comment]
@imtravisb sorry to hear that. I hope you'll give it another chance once it's resolved.

I've been able to reproduce it and I'm in touch with VSTS team.

**Comment by csolarz** [comment]
Today appears the option "Yarn task" in preview mode, that solves my problem and i didnt make any changes in my build definitions.

![image](https://user-images.githubusercontent.com/3832225/48481278-b1231f80-e7eb-11e8-949d-f96757fc55a1.png)

**Comment by sandorfr** [comment]
what do you mean by preview mode?

**Comment by csolarz** [comment]
@sandorfr 

![image](https://user-images.githubusercontent.com/3832225/48486848-5b567380-e7fb-11e8-88fc-3ba0ae8379f4.png)

**Comment by sandorfr** [comment]
Hi 

@csolarz, @imtravisb @NiclasSparrSpoton @youfoundkris, there was an installation issue that has been resolved my Azure devops last week. You should be able to use both tasks now. Also, #57 and #58 have been resolved so you shouldn't see that preview flag anymore.

Let me know how you go.

Kind regards.
