### ISSUE TITLE
File not found: '********\npmauth.js'

### ISSUE THREAD

**Issue by larsklingenberg** [geeklearningio/gl-vsts-tasks-yarn#57]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description
When running yarn in Azure DevOps-pipeline I get the following message:
2018-11-14T10:55:14.0277545Z ##[error]File not found: 'D:\a\_tasks\Yarn_0888c9a9-d1b2-4567-aae2-beadcb2059b3\2.6.999\npmauth.js'

This makes the build fail. 

I have just added Yarn with UI in Azure DevOps-Pipeline. 

Worked for Version 2.5.999, not for 2.6.999.

```
MANDATORY FOR BUGS: Insert debug trace
```
2018-11-14T10:55:13.9869500Z ##[section]Starting: Yarn 
2018-11-14T10:55:13.9872914Z ==============================================================================
2018-11-14T10:55:13.9872988Z Task         : Yarn task
2018-11-14T10:55:13.9873033Z Description  : Executes Yarn
2018-11-14T10:55:13.9873095Z Version      : 2.6.999
2018-11-14T10:55:13.9873139Z Author       : Geek Learning
2018-11-14T10:55:13.9873215Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn) (Version 2.6.999).

Dear Angular and Ember CLI users, please check our [known issues](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Known-Issues)
2018-11-14T10:55:13.9873302Z ==============================================================================
2018-11-14T10:55:14.0277545Z ##[error]File not found: 'D:\a\_tasks\Yarn_0888c9a9-d1b2-4567-aae2-beadcb2059b3\2.6.999\npmauth.js'
2018-11-14T10:55:14.0293835Z ##[section]Finishing: Yarn 

# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [X] Hosted
* [ ] Custom

**OS:**
* [X] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:** 1.9.4 (local)
*Yarn version** 

**Node version:** 10.10
*Node version**

**Comment by larsklingenberg** [comment]
[logs_158.zip](https://github.com/geeklearningio/gl-vsts-tasks-yarn/files/2580620/logs_158.zip)

**Comment by falecci** [comment]
We are having the same problem in Azure DevOps with Hosted VS2017 and Ubuntu agents. Also, we have noticed that we have a "PREVIEW" label in yarn task we didn't have before.

**Comment by marianoheller** [comment]
Same situation as @falecci but without the "PREVIEW" label in the yarn task.

**Comment by ivanfranco502** [comment]
Same here!

**Comment by arichiardi** [comment]
We are affetcted as well.

I converted the `Yarn` tasks to `Command Line` tasks doing the authentication with `npm Authenticate (for task runners)` out of band.

Not ideal though.

**Comment by sandorfr** [comment]
Can you tell me which region your vsts is hosted in?

Le jeu. 15 nov. 2018 à 08:12, Andrea Richiardi <notifications@github.com> a
écrit :

**Comment by arichiardi** [comment]
How do I check that?

**Comment by jogonzal** [comment]
@arichiardi your workaround worked for us too, but agree, not ideal

![image](https://user-images.githubusercontent.com/6866265/48518710-4c81b800-e81f-11e8-8e1a-1db0a7445c89.png)

**Comment by arichiardi** [comment]
@sandorfr `canadacentral`

**Comment by chevonc** [comment]
Any chance we can have a quick reversion on this - while you investigate?

**Comment by sandorfr** [comment]
@chevonc Sadly I can't do anything as it has nothing to do with the tasks and it is a vsts issue. I seems to be related to the last update as it's not affecting all deployment rings.

**Comment by larsklingenberg** [comment]
New version worked for me @sandorfr, thank you! :)

**Comment by sandorfr** [comment]
@stephenmichaelf I get from your question that you are still facing some issues?

**Comment by arichiardi** [comment]
Sorry haven't tried, at the moment I will keep the Command Line tasks instead. Thanks for the quick fix though!

**Comment by stephenmichaelf** [comment]
@sandorfr Nope! I am on the team at Microsoft that owns this so wanted to make sure no one else was having issues :)

**Comment by sandorfr** [comment]
@stephenmichaelf Yes I didn't realize it was you Ross mentioned in his email. Thanks.
