### ISSUE TITLE
VSTS/DevOps - npm private feed 401

### ISSUE THREAD

**Issue by Venipa** [geeklearningio/gl-vsts-tasks-yarn#64]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description

- installed yarn via extension
- run yarn install with vsts feed

# Expected behavior

200 instead of 401 Unauthorized

# Reproduction

Create feed, create build CI with yarn as install

```
info If you think this is a bug, please open a bug report with the information provided in "/vsts/agent/_work/1/s/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]Error: The process '/opt/hostedtoolcache/yarn/1.15.2/x64/yarn-v1.15.2/bin/yarn' failed with exit code 1
```
yarn-error.log shows the yarn.lock
*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [ ] Hosted
* [x] Custom

**OS:**
* [ ] Windows
* [ ] Mac
* [x] Linux

**Yarn version:**
1.15.2

**Node version:**
(10.15)

used with docker
https://github.com/Microsoft/vsts-agent-docker

**Comment by sandorfr** [comment]
Hi, 
Could you please try with the 3.0 version?
If it does not help please provide the full trace in debug mode with yarn in `--verbose`

**Comment by sandorfr** [comment]
Closing, if it's still a problem for you let me know I'll reopen

**Comment by bamminger** [comment]
@sandorfr Works fine with 3.0 preview. Thank you!

**Comment by Venipa** [comment]
```
 "https://****.pkgs.visualstudio.com/_packaging/*****-Feed/npm/registry/@angular/common/-/common-8.2.3.tgz: Request failed \"401 Unauthorized\"".```
leaves just me
