### ISSUE TITLE
Wont execute - wrong agent version

### ISSUE THREAD

**Issue by Jonesie** [geeklearningio/gl-vsts-tasks-yarn#80]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description
When I try to execute a build, the result is:
![image](https://user-images.githubusercontent.com/3420249/77396515-c6a95000-6e08-11ea-8964-26d4d84be05f.png)

*Insert your description here*
I have agent version 2.165.  Do I need to revert to an earlier version or can I force the yarn task (and npm I guess) to use my slightly later version?

# Expected behavior
It should work?

# Reproduction

Create an azure pipeline yaml with the following task:

    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
      displayName: 'Install front end packages'
      inputs:
        projectDirectory: 'src/projectname'

```
MANDATORY FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [ ] VSTS
* [ ] TFS
* [x] Azure DevOps

**Agent:**
* [ ] Hosted
* [X] Custom

**OS:**
* [X] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
*Yarn version**

**Node version:**
*Node version**

**Comment by sandorfr** [comment]
As the error specifies the missing `yarn` capability is what blocks your build. You can use the [Yarn Installer task ](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn-Installer) or install it yourself an manually add the capability to your agents.

**Comment by Jonesie** [comment]
> As the error specifies the missing `yarn` capability is what blocks your build. You can use the [Yarn Installer task ](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn-Installer) or install it yourself an manually add the capability to your agents.

I have yarn installed.

**Comment by johannwalder** [comment]
I have noticed the same issue and solved it by adding "yarn" to the build agent capabilities (as yarn itself is installed). This setting seems not to be needed when using hosted agents (windows2019 in my test case) but it's "needed" for the private build agent that I have created from the windows2019 packer file (https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Azure.json)

The real solution might be different but at least this workaround is working for us.

**Comment by sandorfr** [comment]
If you install yarn on your agent (instead of using the yarn installer)
adding the capability to your agent is the way to go.

If I remove the demanda from the task, it will remove this need but it will
also not prompt people to add what’s necessary so I think I’ll keep the
demand.

**Comment by Jonesie** [comment]
Seems resolved to me.  Thanks
