### ISSUE TITLE
info There appears to be trouble with you network connection

### ISSUE THREAD

**Issue by jauggy** [geeklearningio/gl-vsts-tasks-yarn#84]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [ x] Bug
* [ ] Feature request

# Description
![image](https://user-images.githubusercontent.com/1305569/91408329-0cba8200-e887-11ea-8f78-2e211e9a8146.png)

# Expected behavior

Install packages

# Reproduction
I created a pipeline in Azure Devops.
I added this repo: https://gitlab.com/joshua.augustinus/vc-portal-coreui.git
I add the following tasks to the agent job:
1. Yarn Tool Installer (I didn't change any settings)
2. Yarn task (I didn't change any settings)

```
MANDATORY FOR BUGS: Insert debug trace
```
Raw logs:
https://dev.azure.com/jauggy0098/a98a4eb7-6a58-4ff9-b696-10872cb62235/_apis/build/builds/5/logs/12

# System information

**VSTS or TFS:**
* [ x] VSTS
* [ ] TFS

**Agent:**
* [x ] Hosted
* [ ] Custom

**OS:**
* [x ] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
1.x

**Node version:**
*Node version**

**Comment by sandorfr** [comment]
This looks like a network issue.

**Comment by jauggy** [comment]
Does this mean I just need to contact Azure support?

**Comment by jauggy** [comment]
OK I think I may have solved the issue. You need to add the following argument when using yarn task:
```
install --network-timeout 1000000
```

**Comment by walliski** [comment]
@jauggy Can confirm. I saw the same issue with Microsoft hosted agents in DevOps. Even when using their own Artifacts registry. Increasing the timeout has prevented those issues.

**Comment by martindpinter** [comment]
> OK I think I may have solved the issue. You need to add the following argument when using yarn task:
> 
> ```
> install --network-timeout 1000000
> ```

Can confirm too. yarn install succeeded at worst around 7 minutes.

**Comment by EbenZhang** [comment]
for me it seems only happen on Windows agent. Ubuntu agent is much faster.

**Comment by solacens** [comment]
It happens alot with both Windows or Ubuntu agent.
We are temporarily using private agent to bypass the error.
Still unsolved?
