### ISSUE TITLE
Azure Devops: Yarn task failing intermittently

### ISSUE THREAD

**Issue by shakum23** [geeklearningio/gl-vsts-tasks-yarn#97]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description

*Yarn task is failing in our CI pipelines intermittently. There is no fixed pattern as such. The same pipeline runs successfully sometimes without any modifications. Usually succeeds after 2-3 retries.*

# Expected behavior

*The task should not fail intermittently*

# Reproduction

*Issue is intermittent, no specific steps as such*

```
MANDATORY FOR BUGS: Insert debug trace
[30_Yarn test (mobile) [test].txt](https://github.com/geeklearningio/gl-vsts-tasks-yarn/files/6936471/30_Yarn.test.mobile.test.txt)

```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [x] VSTS
* [ ] TFS

**Agent:**
* [x] Hosted
* [ ] Custom

**OS:**
* [x] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
*1.22.5*

**Node version:**
*12.14.1*

**Comment by sandorfr** [comment]
Can't really help with so little information.
